---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: appx
  namespace: apps-preview
  labels:
    fluxcd.controlplane.io/preview: apps
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "1m"
spec:
  type: GitHubPullRequest
  url: https://github.com/middlewaregruppen/flux-appx
  filter:
    labels:
      - "deploy/flux-preview"
  defaultValues:
    repo: "https://github.com/middlewaregruppen/flux-appx"
    image: "ghcr.io/middlewaregruppen/flux-appx"
    replicas: 2

